apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: traefik-hpa
  namespace: kube-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: traefik
  minReplicas: 1
  maxReplicas: 10
  metrics:
#    - type: Pods
#      pods:
#        metric:
#          name: traefik_tcp_connections
#        target:
#          type: AverageValue
#          averageValue: 5
    - type: Pods
      pods:
        metric:
          name: traefik_http_requests
        target:
          type: AverageValue
          averageValue: 5

