apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-rodo-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-rodo
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: rodo-metrics
        target:
          type: AverageValue
          averageValue: "0.1"



