apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beta
  name: hello-rodo
  labels:
    app: hello-rodo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-rodo
  template:
    metadata:
      labels:
        app: hello-rodo
    spec:
      containers:
        - name: hello-container
          image: rodolgiaco/hello-rodo:1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 9000
          env:
            - name: JVM_OPTIONS
              value: "-Xms1024m -Xmx4072m"
