apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-adapter
  template:
    metadata:
      labels:
        app: prometheus-adapter
    spec:
      serviceAccountName: default
      containers:
        - name: prometheus-adapter
          image: registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.2
          args:
            - /adapter
            - --secure-port=6443
            - --cert-dir=/tmp/cert
            - --prometheus-url=http://prometheus.beta.svc:9090
            - --metrics-relist-interval=1m
            - --config=/etc/adapter/config.yaml
            - --v=6  # Nivel de logs detallado
          ports:
            - name: https
              containerPort: 6443
          volumeMounts:
            - name: config
              mountPath: /etc/adapter/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: prometheus-adapter
