apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  namespace: beta
  labels:
    app: prometheus-adapter
spec:
  ports:
    - port: 443
      targetPort: 6443
  selector:
    app: prometheus-adapter
