# prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: beta
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'traefik'
        static_configs:
          - targets: ['traefik.beta.svc.cluster.local:9100']



