apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: default
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-default
    helm.sh/chart: traefik-27.0.2
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: "-"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-default
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30000
    - port: 443
      name: "websecure"
      targetPort: websecure
      protocol: TCP