apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello-rodov2
  labels:
    app: hello-rodov2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-rodov2
  template:
    metadata:
      labels:
        app: hello-rodov2
    spec:
      containers:
        - name: hello-containerv2
          image: rodolgiaco/hello-rodo:1.2
          ports:
            - containerPort: 8080
          env:
            - name: JVM_OPTIONS
              value: "-Xms1024m -Xmx4072m"