#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: default
#  name: hello-rodo
#  labels:
#    app: hello-rodo
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: hello-rodo
#  template:
#    metadata:
#      labels:
#        app: hello-rodo
#    spec:
#      containers:
#        - name: hello-container
#          image: busybox
#          args:
#            - /bin/sh
#            - -c
#            - |
#              while true; do echo "HTTP/1.1 500 Internal Server Error\n\n" | nc -l -p 8080; done
#          ports:
#            - containerPort: 8080
#          env:
#            - name: JVM_OPTIONS
#              value: "-Xms1024m -Xmx4072m"
