kind: Service
apiVersion: v1
metadata:
  namespace: default
  name:  hello-rodo-service
  labels:
    service: hello-rodo
spec:
  type: NodePort
  ports:
    - port: 1234
      targetPort:  8080
  selector:
    app: hello-rodo
