---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-hello-rodov1
  namespace: beta
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-rodov1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: sugal
          selector:
            matchLabels:
              host: kuberodo.ddns.net
        target:
          type: AverageValue
          averageValue: 500m
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 80

