apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: beta
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
    - protocol: TCP
      port: 443
      targetPort: 443
      name: websecure
    - protocol: TCP
      port: 12093
      targetPort: 12093
      name: tcp
  selector:
    app: traefik