apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: playback-tls-option
  namespace: default
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  curvePreferences:
    - CurveP521
    - CurveP384
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_RSA_WITH_AES_256_GCM_SHA384
  sniStrict: true
  alpnProtocols:
    - h2
    - http/1.1
