apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress
    namespace: beta
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - host: kuberodo.ddns.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-rodo-servicev2
                port:
                  number: 1234


